[package]
name = "scope_lambda"
version = "0.1.0"
edition = "2021"

[build-dependencies]
lalrpop = "0.19.8"

[dependencies]
lalrpop-util = { version = "0.19.8", features = ["lexer"] }
regex = "1"
dialoguer = { version = "0.10.1", features = ["history"] }
